export default plantNames = [
  'Cactus Everdeen',
  'Elvis Parsley',
  'Morgan Treeman',
  'Orlando Bloom',
  'George Bush',
  'Tree Diddy',
  'Vincent Van Grow',
  'Christofern',
  'Fernie Sanders',
  'Robert Planttinson',
  'Diana Moss',
  'Count Plantula',
  'Aloe Vera Wang',
  'Spike Leaf',
  'Hugh Plant',
  'Leafam Neeson',
  'Botany Spears',
  'Oleafia Newton John',
  'Nataleaf Portman',
  'Succmantha Jones',
  'Harry Pot-ter',
  'Lucifern',
  'Huckleberry Fern',
  'Willow Smith',
  'Bamboo-lina Jolie',
  'Leafy Longstocking',
  'Albert Fernstein',
  'Fern Gully',
  'Oprah Stemfrey',
  'Twiggy Smalls',
  'Flora the Explorer',
  'Twiggy Stardust',
  'Palmela Anderson',
  'Twiggy Pop',
  'Twiggy Azalea',
];
